### ISSUE TITLE
Git-Einstellung vornehmen

### ISSUE THREAD

**Issue by Mac10goesBRRRT** [HSFD-WS-24-25/demo-repository#1]
Committer sollten nur auf eigene Branches comitten können, damit Änderungen nichts am laufenden Code kaputt machen können. Eigene Branches sollten nur ein Item umsetzen, dann gelöscht werden.

Ein Branch wird dann per Pull-Request gemerged. Dafür muss mindestens eine weitere Person den Commit Reviewen, um sicherstellen zu können, dass das Projekt/der Build weiterhin funktioniert.

In der Veranstaltung zeigen wir das am "demo-repository".

**Comment by Mac10goesBRRRT** [comment]
Das wäre mein Vorschlag, wir hätten dann main/master branch, in den nur mit Pull-Request gemerged werden kann. Zusätzlich müssen die commits gesquashed werden, es ist also nur noch ein Commit pro feature in der Git-History zu sehen. Dadurch wird das ganze linear.
![grafik](https://github.com/user-attachments/assets/02e5d53f-07c1-42d1-a1ee-faba2a76b235)

**Comment by EricBergstreisser** [comment]
Wir sollten als Regel einstellen, dass nach einem Merge-Request der Branch, von dem "gemerged" wurde gelöscht wird. Somit räumen wir den nicht mehr nötigen "Müll" auf und es liegen keine ungenutzten Branches herum.

**Comment by Mac10goesBRRRT** [comment]
Die Regel "Require a pull request before merging" muss aktiv sein

**Comment by Mac10goesBRRRT** [comment]
Regeln getestet, Merge durchgeführt, damit abeschlossen
